#############################################################################
# Makefile for building: SCAPES
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  SCAPES.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile SCAPES.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -IApplication -IInterface -ILogic -IStorage -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SCAPES1.0.0
DISTDIR = /home/student/Documents/SCAPES/.tmp/SCAPES1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Storage/flatfileimp.cpp \
		Storage/repository.cpp \
		Storage/repositoryimplementor.cpp \
		Storage/statementlist.cpp \
		Storage/vhash.cpp \
		Logic/compilecontrol.cpp \
		Logic/maincontroller.cpp \
		Interface/compileoption.cpp \
		Interface/filebrowser.cpp \
		Interface/loadoption.cpp \
		Interface/mainwindow.cpp \
		Interface/notifymsg.cpp \
		Interface/saveoption.cpp \
		Application/addstatement.cpp \
		Application/arrayvariable.cpp \
		Application/cmpstatement.cpp \
		Application/creator.cpp \
		Application/dcastatement.cpp \
		Application/dcistatement.cpp \
		Application/endstatement.cpp \
		Application/identifier.cpp \
		Application/integerliteral.cpp \
		Application/jeqstatement.cpp \
		Application/jlsstatement.cpp \
		Application/jmpstatement.cpp \
		Application/jmrstatement.cpp \
		Application/label.cpp \
		Application/movstatement.cpp \
		Application/operand.cpp \
		Application/program.cpp \
		Application/prtstatement.cpp \
		Application/rdistatement.cpp \
		Application/serializable.cpp \
		Application/statement.cpp \
		Application/statementcreator.cpp \
		Application/stringliteral.cpp \
		Application/token.cpp \
		Application/variable.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		flatfileimp.o \
		repository.o \
		repositoryimplementor.o \
		statementlist.o \
		vhash.o \
		compilecontrol.o \
		maincontroller.o \
		compileoption.o \
		filebrowser.o \
		loadoption.o \
		mainwindow.o \
		notifymsg.o \
		saveoption.o \
		addstatement.o \
		arrayvariable.o \
		cmpstatement.o \
		creator.o \
		dcastatement.o \
		dcistatement.o \
		endstatement.o \
		identifier.o \
		integerliteral.o \
		jeqstatement.o \
		jlsstatement.o \
		jmpstatement.o \
		jmrstatement.o \
		label.o \
		movstatement.o \
		operand.o \
		program.o \
		prtstatement.o \
		rdistatement.o \
		serializable.o \
		statement.o \
		statementcreator.o \
		stringliteral.o \
		token.o \
		variable.o \
		moc_mainwindow.o
DIST          = run.sh \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SCAPES.pro Storage/flatfileimp.h \
		Storage/repository.h \
		Storage/repositoryimplementor.h \
		Storage/statementlist.h \
		Storage/vhash.h \
		Logic/compilecontrol.h \
		Logic/maincontroller.h \
		Interface/compileoption.h \
		Interface/filebrowser.h \
		Interface/loadoption.h \
		Interface/mainwindow.h \
		Interface/notifymsg.h \
		Interface/saveoption.h \
		Application/addstatement.h \
		Application/arrayvariable.h \
		Application/cmpstatement.h \
		Application/creator.h \
		Application/dcastatement.h \
		Application/dcistatement.h \
		Application/endstatement.h \
		Application/identifier.h \
		Application/integerliteral.h \
		Application/jeqstatement.h \
		Application/jlsstatement.h \
		Application/jmpstatement.h \
		Application/jmrstatement.h \
		Application/label.h \
		Application/movstatement.h \
		Application/operand.h \
		Application/program.h \
		Application/prtstatement.h \
		Application/rdistatement.h \
		Application/serializable.h \
		Application/statement.h \
		Application/statementcreator.h \
		Application/stringliteral.h \
		Application/token.h \
		Application/variable.h main.cpp \
		Storage/flatfileimp.cpp \
		Storage/repository.cpp \
		Storage/repositoryimplementor.cpp \
		Storage/statementlist.cpp \
		Storage/vhash.cpp \
		Logic/compilecontrol.cpp \
		Logic/maincontroller.cpp \
		Interface/compileoption.cpp \
		Interface/filebrowser.cpp \
		Interface/loadoption.cpp \
		Interface/mainwindow.cpp \
		Interface/notifymsg.cpp \
		Interface/saveoption.cpp \
		Application/addstatement.cpp \
		Application/arrayvariable.cpp \
		Application/cmpstatement.cpp \
		Application/creator.cpp \
		Application/dcastatement.cpp \
		Application/dcistatement.cpp \
		Application/endstatement.cpp \
		Application/identifier.cpp \
		Application/integerliteral.cpp \
		Application/jeqstatement.cpp \
		Application/jlsstatement.cpp \
		Application/jmpstatement.cpp \
		Application/jmrstatement.cpp \
		Application/label.cpp \
		Application/movstatement.cpp \
		Application/operand.cpp \
		Application/program.cpp \
		Application/prtstatement.cpp \
		Application/rdistatement.cpp \
		Application/serializable.cpp \
		Application/statement.cpp \
		Application/statementcreator.cpp \
		Application/stringliteral.cpp \
		Application/token.cpp \
		Application/variable.cpp
QMAKE_TARGET  = SCAPES
DESTDIR       = 
TARGET        = SCAPES


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SCAPES.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SCAPES.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile SCAPES.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
SCAPES.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile SCAPES.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Storage/flatfileimp.h Storage/repository.h Storage/repositoryimplementor.h Storage/statementlist.h Storage/vhash.h Logic/compilecontrol.h Logic/maincontroller.h Interface/compileoption.h Interface/filebrowser.h Interface/loadoption.h Interface/mainwindow.h Interface/notifymsg.h Interface/saveoption.h Application/addstatement.h Application/arrayvariable.h Application/cmpstatement.h Application/creator.h Application/dcastatement.h Application/dcistatement.h Application/endstatement.h Application/identifier.h Application/integerliteral.h Application/jeqstatement.h Application/jlsstatement.h Application/jmpstatement.h Application/jmrstatement.h Application/label.h Application/movstatement.h Application/operand.h Application/program.h Application/prtstatement.h Application/rdistatement.h Application/serializable.h Application/statement.h Application/statementcreator.h Application/stringliteral.h Application/token.h Application/variable.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp Storage/flatfileimp.cpp Storage/repository.cpp Storage/repositoryimplementor.cpp Storage/statementlist.cpp Storage/vhash.cpp Logic/compilecontrol.cpp Logic/maincontroller.cpp Interface/compileoption.cpp Interface/filebrowser.cpp Interface/loadoption.cpp Interface/mainwindow.cpp Interface/notifymsg.cpp Interface/saveoption.cpp Application/addstatement.cpp Application/arrayvariable.cpp Application/cmpstatement.cpp Application/creator.cpp Application/dcastatement.cpp Application/dcistatement.cpp Application/endstatement.cpp Application/identifier.cpp Application/integerliteral.cpp Application/jeqstatement.cpp Application/jlsstatement.cpp Application/jmpstatement.cpp Application/jmrstatement.cpp Application/label.cpp Application/movstatement.cpp Application/operand.cpp Application/program.cpp Application/prtstatement.cpp Application/rdistatement.cpp Application/serializable.cpp Application/statement.cpp Application/statementcreator.cpp Application/stringliteral.cpp Application/token.cpp Application/variable.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Interface/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: Logic/maincontroller.h \
		Application/program.h \
		Storage/vhash.h \
		Application/identifier.h \
		Application/serializable.h \
		Storage/statementlist.h \
		Application/statement.h \
		Application/operand.h \
		Application/label.h \
		Application/token.h \
		Storage/repository.h \
		Storage/repositoryimplementor.h \
		Interface/mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/SCAPES -I/home/student/Documents/SCAPES/Application -I/home/student/Documents/SCAPES/Interface -I/home/student/Documents/SCAPES/Logic -I/home/student/Documents/SCAPES/Storage -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Interface/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: Interface/mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Interface/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp Interface/mainwindow.h \
		Logic/maincontroller.h \
		Application/program.h \
		Storage/vhash.h \
		Application/identifier.h \
		Application/serializable.h \
		Storage/statementlist.h \
		Application/statement.h \
		Application/operand.h \
		Application/label.h \
		Application/token.h \
		Storage/repository.h \
		Storage/repositoryimplementor.h \
		Storage/flatfileimp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

flatfileimp.o: Storage/flatfileimp.cpp Storage/flatfileimp.h \
		Storage/repositoryimplementor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flatfileimp.o Storage/flatfileimp.cpp

repository.o: Storage/repository.cpp Storage/repository.h \
		Storage/repositoryimplementor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o repository.o Storage/repository.cpp

repositoryimplementor.o: Storage/repositoryimplementor.cpp Storage/repositoryimplementor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o repositoryimplementor.o Storage/repositoryimplementor.cpp

statementlist.o: Storage/statementlist.cpp Storage/statementlist.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statementlist.o Storage/statementlist.cpp

vhash.o: Storage/vhash.cpp Storage/vhash.h \
		Application/identifier.h \
		Application/serializable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vhash.o Storage/vhash.cpp

compilecontrol.o: Logic/compilecontrol.cpp Logic/compilecontrol.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h \
		Storage/statementlist.h \
		Application/statementcreator.h \
		Application/creator.h \
		Application/dcistatement.h \
		Application/dcastatement.h \
		Application/rdistatement.h \
		Application/addstatement.h \
		Application/jmpstatement.h \
		Application/jmrstatement.h \
		Application/jlsstatement.h \
		Application/jeqstatement.h \
		Application/endstatement.h \
		Application/cmpstatement.h \
		Application/movstatement.h \
		Application/prtstatement.h \
		Application/variable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compilecontrol.o Logic/compilecontrol.cpp

maincontroller.o: Logic/maincontroller.cpp Logic/maincontroller.h \
		Application/program.h \
		Storage/vhash.h \
		Application/identifier.h \
		Application/serializable.h \
		Storage/statementlist.h \
		Application/statement.h \
		Application/operand.h \
		Application/label.h \
		Application/token.h \
		Storage/repository.h \
		Storage/repositoryimplementor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maincontroller.o Logic/maincontroller.cpp

compileoption.o: Interface/compileoption.cpp Interface/compileoption.h \
		Logic/maincontroller.h \
		Application/program.h \
		Storage/vhash.h \
		Application/identifier.h \
		Application/serializable.h \
		Storage/statementlist.h \
		Application/statement.h \
		Application/operand.h \
		Application/label.h \
		Application/token.h \
		Storage/repository.h \
		Storage/repositoryimplementor.h \
		Interface/notifymsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compileoption.o Interface/compileoption.cpp

filebrowser.o: Interface/filebrowser.cpp Interface/filebrowser.h \
		Interface/mainwindow.h \
		Logic/maincontroller.h \
		Application/program.h \
		Storage/vhash.h \
		Application/identifier.h \
		Application/serializable.h \
		Storage/statementlist.h \
		Application/statement.h \
		Application/operand.h \
		Application/label.h \
		Application/token.h \
		Storage/repository.h \
		Storage/repositoryimplementor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filebrowser.o Interface/filebrowser.cpp

loadoption.o: Interface/loadoption.cpp Interface/loadoption.h \
		Interface/mainwindow.h \
		Logic/maincontroller.h \
		Application/program.h \
		Storage/vhash.h \
		Application/identifier.h \
		Application/serializable.h \
		Storage/statementlist.h \
		Application/statement.h \
		Application/operand.h \
		Application/label.h \
		Application/token.h \
		Storage/repository.h \
		Storage/repositoryimplementor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loadoption.o Interface/loadoption.cpp

mainwindow.o: Interface/mainwindow.cpp Interface/mainwindow.h \
		Logic/maincontroller.h \
		Application/program.h \
		Storage/vhash.h \
		Application/identifier.h \
		Application/serializable.h \
		Storage/statementlist.h \
		Application/statement.h \
		Application/operand.h \
		Application/label.h \
		Application/token.h \
		Storage/repository.h \
		Storage/repositoryimplementor.h \
		ui_mainwindow.h \
		Interface/compileoption.h \
		Interface/saveoption.h \
		Interface/loadoption.h \
		Interface/filebrowser.h \
		Interface/notifymsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o Interface/mainwindow.cpp

notifymsg.o: Interface/notifymsg.cpp Interface/notifymsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o notifymsg.o Interface/notifymsg.cpp

saveoption.o: Interface/saveoption.cpp Interface/saveoption.h \
		Interface/mainwindow.h \
		Logic/maincontroller.h \
		Application/program.h \
		Storage/vhash.h \
		Application/identifier.h \
		Application/serializable.h \
		Storage/statementlist.h \
		Application/statement.h \
		Application/operand.h \
		Application/label.h \
		Application/token.h \
		Storage/repository.h \
		Storage/repositoryimplementor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o saveoption.o Interface/saveoption.cpp

addstatement.o: Application/addstatement.cpp Application/addstatement.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addstatement.o Application/addstatement.cpp

arrayvariable.o: Application/arrayvariable.cpp Application/arrayvariable.h \
		Application/identifier.h \
		Application/serializable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arrayvariable.o Application/arrayvariable.cpp

cmpstatement.o: Application/cmpstatement.cpp Application/cmpstatement.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmpstatement.o Application/cmpstatement.cpp

creator.o: Application/creator.cpp Application/creator.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o creator.o Application/creator.cpp

dcastatement.o: Application/dcastatement.cpp Application/dcastatement.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h \
		Application/arrayvariable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dcastatement.o Application/dcastatement.cpp

dcistatement.o: Application/dcistatement.cpp Application/dcistatement.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h \
		Application/variable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dcistatement.o Application/dcistatement.cpp

endstatement.o: Application/endstatement.cpp Application/endstatement.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o endstatement.o Application/endstatement.cpp

identifier.o: Application/identifier.cpp Application/identifier.h \
		Application/serializable.h \
		Application/stringliteral.h \
		Application/integerliteral.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o identifier.o Application/identifier.cpp

integerliteral.o: Application/integerliteral.cpp Application/integerliteral.h \
		Application/identifier.h \
		Application/serializable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integerliteral.o Application/integerliteral.cpp

jeqstatement.o: Application/jeqstatement.cpp Application/jeqstatement.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jeqstatement.o Application/jeqstatement.cpp

jlsstatement.o: Application/jlsstatement.cpp Application/jlsstatement.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jlsstatement.o Application/jlsstatement.cpp

jmpstatement.o: Application/jmpstatement.cpp Application/jmpstatement.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jmpstatement.o Application/jmpstatement.cpp

jmrstatement.o: Application/jmrstatement.cpp Application/jmrstatement.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jmrstatement.o Application/jmrstatement.cpp

label.o: Application/label.cpp Application/label.h \
		Application/identifier.h \
		Application/serializable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o label.o Application/label.cpp

movstatement.o: Application/movstatement.cpp Application/movstatement.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movstatement.o Application/movstatement.cpp

operand.o: Application/operand.cpp Application/operand.h \
		Application/identifier.h \
		Application/serializable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o operand.o Application/operand.cpp

program.o: Application/program.cpp Application/program.h \
		Storage/vhash.h \
		Application/identifier.h \
		Application/serializable.h \
		Storage/statementlist.h \
		Application/statement.h \
		Application/operand.h \
		Application/label.h \
		Application/token.h \
		Logic/compilecontrol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o program.o Application/program.cpp

prtstatement.o: Application/prtstatement.cpp Application/prtstatement.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prtstatement.o Application/prtstatement.cpp

rdistatement.o: Application/rdistatement.cpp Application/rdistatement.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rdistatement.o Application/rdistatement.cpp

serializable.o: Application/serializable.cpp Application/serializable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serializable.o Application/serializable.cpp

statement.o: Application/statement.cpp Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h \
		Application/arrayvariable.h \
		Application/integerliteral.h \
		Application/stringliteral.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statement.o Application/statement.cpp

statementcreator.o: Application/statementcreator.cpp Application/statementcreator.h \
		Application/creator.h \
		Application/statement.h \
		Application/operand.h \
		Application/identifier.h \
		Application/serializable.h \
		Application/label.h \
		Storage/vhash.h \
		Application/token.h \
		Application/dcistatement.h \
		Application/dcastatement.h \
		Application/rdistatement.h \
		Application/addstatement.h \
		Application/jmpstatement.h \
		Application/jmrstatement.h \
		Application/jlsstatement.h \
		Application/jeqstatement.h \
		Application/endstatement.h \
		Application/cmpstatement.h \
		Application/movstatement.h \
		Application/prtstatement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statementcreator.o Application/statementcreator.cpp

stringliteral.o: Application/stringliteral.cpp Application/stringliteral.h \
		Application/identifier.h \
		Application/serializable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stringliteral.o Application/stringliteral.cpp

token.o: Application/token.cpp Application/token.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o token.o Application/token.cpp

variable.o: Application/variable.cpp Application/variable.h \
		Application/identifier.h \
		Application/serializable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o variable.o Application/variable.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/SCAPES/bin || mkdir -p $(INSTALL_ROOT)/opt/SCAPES/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/SCAPES/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/SCAPES/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/SCAPES/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/SCAPES/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

